/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mcaj.gui;

import br.com.mcaj.bdimg.ManipularImagem;
import br.com.mcaj.bean.BeanCliente;
import br.com.mcaj.dao.DaoCadCliente;
import br.com.mcaj.metodos.TratamentoData;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Marcos
 */
public class BuscaCliente extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private TableRowSorter<TableModel> trs;
    private int campoPesquisa;

    /**
     * Creates new form BuscaCliente
     */
    public BuscaCliente() throws SQLException {
        initComponents();
        modelo = (DefaultTableModel) tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));

        CarregarTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        cboCampoEscolhido = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Buscar Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        tabela.setAutoCreateRowSorter(true);
        tabela.setBackground(new java.awt.Color(255, 204, 255));
        tabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabela.setForeground(new java.awt.Color(0, 0, 0));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Foto do Cliente", "Nome", "Documento", "Tipo", "Data Nasc.", "E-mail", "Tel", "Cel", "NomeRecado", "TelRecado", "CelRecado", "Cep", "Endereco", "Bairro", "Cidade", "UF", "Nº", "Complemento", "Referencia", "Foto da Casa", "Seleciona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Byte.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setToolTipText("");
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabela.setGridColor(new java.awt.Color(0, 0, 0));
        tabela.setName(""); // NOI18N
        tabela.setShowHorizontalLines(true);
        tabela.setShowVerticalLines(true);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, 30));

        cboCampoEscolhido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nome", "Documento", "Tipo", "DataNasc.", "E-mail", "Tel", "Cel", "NomeRecado", "TelRecado", "CelRecado", "CEP", "Endereco", "Bairro", "Cidade", "UF", "Nº", "Complemento", "Referencia" }));
        jPanel3.add(cboCampoEscolhido, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 270, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        txtBuscar.addKeyListener(new KeyAdapter() {

            public void keyReleased(final KeyEvent e) {

                if (cboCampoEscolhido.getSelectedIndex() == 0) {
                    campoPesquisa = 0; // codigo
                } else if (cboCampoEscolhido.getSelectedIndex() == 1) {
                    campoPesquisa = 2;// nome
                } else if (cboCampoEscolhido.getSelectedIndex() == 2) {
                    campoPesquisa = 3;// documento
                } else if (cboCampoEscolhido.getSelectedIndex() == 3) {
                    campoPesquisa = 4;//tipo documento
                } else if (cboCampoEscolhido.getSelectedIndex() == 4) {
                    campoPesquisa = 5;//data de nascimento
                } else if (cboCampoEscolhido.getSelectedIndex() == 5) {
                    campoPesquisa = 6;// e-mail
                } else if (cboCampoEscolhido.getSelectedIndex() == 6) {
                    campoPesquisa = 7;//telefone
                } else if (cboCampoEscolhido.getSelectedIndex() == 7) {
                    campoPesquisa = 8;//celular
                } else if (cboCampoEscolhido.getSelectedIndex() == 8) {
                    campoPesquisa = 9;//nome recado
                } else if (cboCampoEscolhido.getSelectedIndex() == 9) {
                    campoPesquisa = 10;//tel recado
                } else if (cboCampoEscolhido.getSelectedIndex() == 10) {
                    campoPesquisa = 11;//cel recado
                } else if (cboCampoEscolhido.getSelectedIndex() == 11) {
                    campoPesquisa = 12;//cep
                } else if (cboCampoEscolhido.getSelectedIndex() == 12) {
                    campoPesquisa = 13;//endereco
                } else if (cboCampoEscolhido.getSelectedIndex() == 13) {
                    campoPesquisa = 14;//bairro
                } else if (cboCampoEscolhido.getSelectedIndex() == 14) {
                    campoPesquisa = 15;//cidade
                } else if (cboCampoEscolhido.getSelectedIndex() == 15) {
                    campoPesquisa = 16;//uf
                } else if (cboCampoEscolhido.getSelectedIndex() == 16) {
                    campoPesquisa = 17;//numero residencia
                } else if (cboCampoEscolhido.getSelectedIndex() == 17) {
                    campoPesquisa = 18;//complemento
                } else if (cboCampoEscolhido.getSelectedIndex() == 18) {
                    campoPesquisa = 19;//referencia
                }

                habilitarFiltragemBuscaTabela();

                trs.setRowFilter(RowFilter.regexFilter(
                        "(?i)" + txtBuscar.getText(), campoPesquisa));
                if (txtBuscar.getText().equals("")) {
                    //limparFiltro();
                }

            }

        });
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            Date data = null;
            int linha = tabela.getSelectedRow();

            String codigo = tabela.getValueAt(linha, 0).toString();
            Byte foto = (Byte) tabela.getValueAt(linha, 1);

            String nome = tabela.getValueAt(linha, 2).toString();
            String documento = tabela.getValueAt(linha, 3).toString();
            String tipo = tabela.getValueAt(linha, 4).toString();
            //    String dataNascimento = tabela.getValueAt(linha, 5).toString();
            String email = tabela.getValueAt(linha, 6).toString();
            String tel = tabela.getValueAt(linha, 7).toString();
            String cel = tabela.getValueAt(linha, 8).toString();
            String nomeRecado = tabela.getValueAt(linha, 9).toString();
            String telRecado = tabela.getValueAt(linha, 10).toString();
            String celRecado = tabela.getValueAt(linha, 11).toString();
            String cep = tabela.getValueAt(linha, 12).toString();
            String end = tabela.getValueAt(linha, 13).toString();
            String bairro = tabela.getValueAt(linha, 14).toString();
            String cidade = tabela.getValueAt(linha, 15).toString();
            String uf = tabela.getValueAt(linha, 16).toString();
            String numResidencia = tabela.getValueAt(linha, 17).toString();
            String complemento = tabela.getValueAt(linha, 18).toString();
            String referencia = tabela.getValueAt(linha, 19).toString();
            DaoCadCliente dao = new DaoCadCliente();

            dispose();
            CadastroCliente app = new CadastroCliente();
            app.setVisible(true);

            app.recebeDadosBusca(codigo, foto, nome, documento, tipo, email, tel, cel, nomeRecado, telRecado, celRecado, cep, end, bairro, cidade, uf, numResidencia, complemento, referencia);

            app.setCampos(true, true, true, true, true,
                    true, true, true, true, true, true,
                    true, true, true, true, true, true, true,
                    true, true, true, false, true, true, true);

            app.setBotoes(false, true, true, false, true, true, true);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja mesmo Fechar a Tela?", "Atenção", JOptionPane.YES_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            dispose();
            Menu menu = new Menu();
            menu.setVisible(true);

        }


    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BuscaCliente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BuscaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCampoEscolhido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    public void CarregarTabela() throws SQLException {
        confDaTabela();
        DaoCadCliente dao = new DaoCadCliente();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        TratamentoData trataData = new TratamentoData();

        for (BeanCliente cliente : dao.buscarTodos()) {
            modelo.addRow(new Object[]{
                cliente.getCodigo(),//na tabela
                cliente.getImgCliente(),
                cliente.getNome(),//na tabela
                cliente.getDocumento(),//na tabela
                cliente.getTipoDocumento(),//na tabela
                cliente.getDataNascimento(),
                cliente.getEmail(),
                cliente.getTel(),
                cliente.getCel(),
                cliente.getNomeRecado(),
                cliente.getTelRecado(),
                cliente.getCelRecado(),
                cliente.getCep(),
                cliente.getEndereco(),
                cliente.getBairro(),
                cliente.getCidade(),
                cliente.getUf(),
                cliente.getNumResidencia(),
                cliente.getComplemento(),
                cliente.getReferencia(),
                cliente.getFotoFaxadaCliente(),});
        }

    }

    public void habilitarFiltragemBuscaTabela() {
        // habilita a filtragem dos dados
        trs = new TableRowSorter<TableModel>(tabela.getModel());
        tabela.setRowSorter(trs);

    }

    public void confDaTabela() {
        tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(220);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(150);
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(4).setResizable(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(80);
        tabela.getColumnModel().getColumn(5).setResizable(false);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(270);
        tabela.getColumnModel().getColumn(6).setResizable(false);
        tabela.getColumnModel().getColumn(7).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(7).setResizable(false);
        tabela.getColumnModel().getColumn(8).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(8).setResizable(false);
        tabela.getColumnModel().getColumn(9).setPreferredWidth(220);
        tabela.getColumnModel().getColumn(9).setResizable(false);
        tabela.getColumnModel().getColumn(10).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(10).setResizable(false);
        tabela.getColumnModel().getColumn(11).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(11).setResizable(false);
        tabela.getColumnModel().getColumn(12).setPreferredWidth(80);
        tabela.getColumnModel().getColumn(12).setResizable(false);
        tabela.getColumnModel().getColumn(13).setPreferredWidth(255);
        tabela.getColumnModel().getColumn(13).setResizable(false);
        tabela.getColumnModel().getColumn(14).setPreferredWidth(280);
        tabela.getColumnModel().getColumn(14).setResizable(false);
        tabela.getColumnModel().getColumn(15).setPreferredWidth(280);
        tabela.getColumnModel().getColumn(15).setResizable(false);
        tabela.getColumnModel().getColumn(16).setPreferredWidth(30);
        tabela.getColumnModel().getColumn(16).setResizable(false);
        tabela.getColumnModel().getColumn(17).setPreferredWidth(80);
        tabela.getColumnModel().getColumn(17).setResizable(false);
        tabela.getColumnModel().getColumn(18).setPreferredWidth(250);
        tabela.getColumnModel().getColumn(18).setResizable(false);
        tabela.getColumnModel().getColumn(19).setPreferredWidth(350);
        tabela.getColumnModel().getColumn(19).setResizable(false);
        tabela.getColumnModel().getColumn(20).setPreferredWidth(150);
        tabela.getColumnModel().getColumn(20).setResizable(false);

        tabela.getTableHeader().setReorderingAllowed(false);

    }

}
