/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mcaj.gui;

import br.com.mcaj.bean.BeanProduto;
import br.com.mcaj.dao.DaoCadProduto;
import br.com.mcaj.metodos.BloqueiaLetrasEnumeros;
import br.com.mcaj.metodos.MetodosCadProduto;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class CadProduto extends javax.swing.JFrame {

    private DaoCadProduto produtoDao;
    private String DesejaGravar, Gravado, nGravar, Cancelar;

    /**
     * Creates new form CadProduto
     */
    public CadProduto() {
        initComponents();
        GrupoRadioButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painel = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lbQtde = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        painelComandos = new javax.swing.JPanel();
        painelDeComandos = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        selecGravar = new javax.swing.JRadioButton();
        selecAtualizar = new javax.swing.JRadioButton();
        btNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        painel.setBackground(new java.awt.Color(102, 102, 255));
        painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        painel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 0, 0));
        lbNome.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lbPreco.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbPreco.setForeground(new java.awt.Color(0, 0, 0));
        lbPreco.setText("Preço");

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        lbQtde.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbQtde.setForeground(new java.awt.Color(0, 0, 0));
        lbQtde.setText("Quantidade");

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });

        painelComandos.setBackground(new java.awt.Color(255, 255, 153));
        painelComandos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comandos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        painelComandos.setLayout(new java.awt.GridLayout(1, 0));

        painelDeComandos.setBackground(new java.awt.Color(204, 255, 204));
        painelDeComandos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Executar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N

        btGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mcaj/gui/imagens/savetheapplication_guardar_2958.png"))); // NOI18N
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });
        painelDeComandos.add(btGravar);
        btGravar.getAccessibleContext().setAccessibleName("btGravar");
        btGravar.getAccessibleContext().setAccessibleDescription("");

        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mcaj/gui/imagens/delete_delete_exit_1577.png"))); // NOI18N
        btDeletar.setText("Deletar");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });
        painelDeComandos.add(btDeletar);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mcaj/gui/imagens/Cancel_icon-icons.com_73703.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        painelDeComandos.add(btCancelar);

        painelComandos.add(painelDeComandos);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escolher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N

        selecGravar.setText("Gravar");
        selecGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecGravarActionPerformed(evt);
            }
        });
        jPanel1.add(selecGravar);

        selecAtualizar.setText("Atualizar");
        selecAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(selecAtualizar);

        painelComandos.add(jPanel1);

        btNovo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Downloads\\1486485588-add-create-new-math-sign-cross-plus_81186.png")); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelComandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome)
                            .addComponent(lbPreco)
                            .addComponent(lbQtde))
                        .addGap(31, 31, 31)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btNovo)
                                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(txtQuantidade)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtde)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(painelComandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 16, 15);
        getContentPane().add(painel, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btCancelarActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, DesejaGravar);
        if (resposta == JOptionPane.YES_OPTION) {
            if (selecGravar.isSelected()) {
                Gravar();
            } // TODO Auto-generated catch block
            if (selecAtualizar.isSelected()) {
                Atualizar();

            }
            JOptionPane.showMessageDialog(null, Gravado);

            // setBotoes(true, false, false, false, false, false, false, false, false, false);
        } else if (resposta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null,
                    nGravar);

            //setBotoes(true, false, false, false, false, false, false, false, false, false);
        } else if (resposta == JOptionPane.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null,
                    Cancelar);

            return;
        }
    }//GEN-LAST:event_btGravarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        // TODO add your handling code here:
        deletar();
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_btNovoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja mesmo fechar essa Tela?", "Atenção", JOptionPane.YES_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
          this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        CarregarProdutos app =  new CarregarProdutos();
        app.limparTabela();
    }//GEN-LAST:event_formWindowClosed

    private void selecGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecGravarActionPerformed
        // TODO add your handling code here:
        DesejaGravar = "Deseja Gravar os Registros?";
        Gravado = "Registros Gravados no Banco!!!";
        nGravar = "Os registros não serão Gravados!!!";
        Cancelar = "Registros não foram Gravados!!!";
        
        MetodosCadProduto app = new MetodosCadProduto();
        app.cmdRdGravar(selecGravar, btGravar);
    }//GEN-LAST:event_selecGravarActionPerformed

    private void selecAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecAtualizarActionPerformed
        // TODO add your handling code here:
        DesejaGravar = "Deseja Atualizar os Registros?";
        Gravado = "Registros Atualizados no Banco!!!";
        nGravar = "Os registros não serão Atualizados!!!";
        Cancelar = "Registros não foram Atualizados!!!";
        
        MetodosCadProduto app = new MetodosCadProduto();
        app.cmdRdAtualizar(selecAtualizar, btGravar);

    }//GEN-LAST:event_selecAtualizarActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
        // TODO add your handling code here:
        BloqueiaLetrasEnumeros bloqueioLetras = new BloqueiaLetrasEnumeros();
        bloqueioLetras.bloqueiaLetras(evt);
    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProduto().setVisible(true);
            }
        });
    }

    public void RecebeInformacao(String nome, String preco, String quantidade) {
        txtNome.setText(nome);
        txtPreco.setText(preco);
        txtQuantidade.setText(quantidade);

    }

    private void LimparCampos() {
        txtNome.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");
    }

    public void Gravar() {
        System.out.println(txtNome.getText());
        System.out.println(txtPreco.getText());
        System.out.println(txtQuantidade.getText());

        DaoCadProduto dao = new DaoCadProduto();
        BeanProduto bean = new BeanProduto();

        bean.setName(txtNome.getText());
        bean.setPrice(Double.parseDouble(txtPreco.getText()));
        bean.setQuantity(Integer.parseInt(txtQuantidade.getText()));

        dao.inserir(bean);
    }

    public void Atualizar() {
        System.out.println(txtNome.getText());
        System.out.println(txtPreco.getText());
        System.out.println(txtQuantidade.getText());

        DaoCadProduto dao = new DaoCadProduto();
        BeanProduto bean = new BeanProduto();

        bean.setName(txtNome.getText());
        bean.setPrice(Double.parseDouble(txtPreco.getText()));
        bean.setQuantity(Integer.parseInt(txtQuantidade.getText()));

        dao.atualizar(bean);
    }

    public void deletar() {
        System.out.println(txtNome.getText());
        System.out.println(txtPreco.getText());
        System.out.println(txtQuantidade.getText());

        DaoCadProduto dao = new DaoCadProduto();
        BeanProduto bean = new BeanProduto();

        bean.setName(txtNome.getText());
        dao.deletar(bean);
    }

    public void GrupoRadioButton() {
        ButtonGroup grupoDeRadios = new ButtonGroup();
        grupoDeRadios.add(selecGravar);
        grupoDeRadios.add(selecAtualizar);

    }
    // teste dando errado 
//    public void Gravar2() {
//        produtoDao = new DaoCadProduto();
//        produtoDao.beanProduto.setName(txtNome.getText());
//        produtoDao.beanProduto.setPrice(Double.parseDouble(txtPreco.getText()));
//        produtoDao.beanProduto.setQuantity(Integer.parseInt(txtQuantidade.getText()));
//
//        JOptionPane.showMessageDialog(null,
//                produtoDao.Atualizar(DaoCadProduto.ALTERACAO));
//       
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btNovo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQtde;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel painelComandos;
    private javax.swing.JPanel painelDeComandos;
    private javax.swing.JRadioButton selecAtualizar;
    private javax.swing.JRadioButton selecGravar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

}
